// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/search-properties.ts
import { createClient } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var search_properties_default = defineTool({
  name: "search_properties",
  title: "Search properties",
  description: "Search published property listings on KenyaHomes. Filter by city, price range, minimum beds/baths, and sale vs rent.",
  inputSchema: {
    city: z.string().trim().optional().describe("City name substring, e.g. 'Nairobi'."),
    min_price: z.number().nonnegative().optional().describe("Minimum price in KES."),
    max_price: z.number().nonnegative().optional().describe("Maximum price in KES."),
    min_beds: z.number().int().nonnegative().optional(),
    min_baths: z.number().int().nonnegative().optional(),
    for_rent: z.boolean().optional().describe("true = rentals, false = for sale. Omit for both."),
    limit: z.number().int().min(1).max(50).optional().describe("Max results (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let q = supabase.from("properties").select("id,title,price,currency,for_rent,beds,baths,city,address,region,area_sqft").eq("status", "published").order("created_at", { ascending: false }).limit(input.limit ?? 20);
    if (input.city) q = q.ilike("city", `%${input.city}%`);
    if (input.min_price !== void 0) q = q.gte("price", input.min_price);
    if (input.max_price !== void 0) q = q.lte("price", input.max_price);
    if (input.min_beds !== void 0) q = q.gte("beds", input.min_beds);
    if (input.min_baths !== void 0) q = q.gte("baths", input.min_baths);
    if (input.for_rent !== void 0) q = q.eq("for_rent", input.for_rent);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-property.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_property_default = defineTool2({
  name: "get_property",
  title: "Get property details",
  description: "Fetch full details for a single KenyaHomes property by id.",
  inputSchema: {
    property_id: z2.string().uuid().describe("Property UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("properties").select("*, property_photos(storage_path,ordering)").eq("id", property_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Property not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { property: data }
    };
  }
});

// src/lib/mcp/tools/list-saved-properties.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_saved_properties_default = defineTool3({
  name: "list_saved_properties",
  title: "List my saved properties",
  description: "List the signed-in user's saved (favourited) properties on KenyaHomes.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("saved_properties").select("id, created_at, properties(id,title,price,currency,for_rent,beds,baths,city,address)").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { saved: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/save-property.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_property_default = defineTool4({
  name: "save_property",
  title: "Save a property",
  description: "Save (favourite) a property for the signed-in user.",
  inputSchema: {
    property_id: z3.string().uuid().describe("Property UUID to save.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("saved_properties").insert({ user_id: ctx.getUserId(), property_id }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved property ${property_id}` }],
      structuredContent: { saved: data }
    };
  }
});

// src/lib/mcp/tools/unsave-property.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^3.25.76";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var unsave_property_default = defineTool5({
  name: "unsave_property",
  title: "Remove a saved property",
  description: "Remove a property from the signed-in user's saved list.",
  inputSchema: {
    property_id: z4.string().uuid().describe("Property UUID to unsave.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ property_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { error } = await supabaseForUser5(ctx).from("saved_properties").delete().eq("user_id", ctx.getUserId()).eq("property_id", property_id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Removed property ${property_id} from saved list` }] };
  }
});

// src/lib/mcp/tools/list-my-listings.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
function supabaseForUser6(ctx) {
  return createClient6(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_listings_default = defineTool6({
  name: "list_my_listings",
  title: "List my property listings",
  description: "For agents: list all property listings owned by the signed-in user, including drafts and unpublished listings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser6(ctx).from("properties").select("id,title,status,price,currency,for_rent,beds,baths,city,address,created_at").eq("agent_id", ctx.getUserId()).order("created_at", { ascending: false });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { listings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-messages.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.81.1";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z5 } from "npm:zod@^3.25.76";
function supabaseForUser7(ctx) {
  return createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_messages_default = defineTool7({
  name: "list_my_messages",
  title: "List my messages",
  description: "List inquiry messages the signed-in user has sent (as a seeker) or received (as the listing agent).",
  inputSchema: {
    role: z5.enum(["sent", "received", "all"]).optional().describe("Filter by role (default 'all')."),
    limit: z5.number().int().min(1).max(100).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ role = "all", limit = 25 }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const uid = ctx.getUserId();
    let q = supabaseForUser7(ctx).from("messages").select("id, property_id, seeker_id, agent_id, body, email, phone, created_at").order("created_at", { ascending: false }).limit(limit);
    if (role === "sent") q = q.eq("seeker_id", uid);
    else if (role === "received") q = q.eq("agent_id", uid);
    else q = q.or(`seeker_id.eq.${uid},agent_id.eq.${uid}`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "olwvgnulpfqqvgfrxqhg";
var mcp_default = defineMcp({
  name: "kenyahomes-mcp",
  title: "KenyaHomes",
  version: "0.1.0",
  instructions: "Tools to search KenyaHomes property listings and manage the signed-in user's saved properties, listings (for agents), and inquiry messages. All tools act as the authenticated user; Row Level Security enforces per-user data access.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_properties_default,
    get_property_default,
    list_saved_properties_default,
    save_property_default,
    unsave_property_default,
    list_my_listings_default,
    list_my_messages_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
